[package]
name = "starry-dex"
version = "0.2.0"
authors = ["mariinkys (kysdev.owjga@aleeas.com)"]
edition = "2021"
description = "A Pokédex application for the COSMIC™ desktop written in Rust"
readme = "https://github.com/mariinkys/starrydex/blob/main/README.md"
repository = "https://github.com/mariinkys/starrydex"
license = "GPL-3.0"

[dependencies]
futures-util = "0.3.31"
i18n-embed-fl = "0.9.1"
once_cell = "1.20.2"
open = "5.3.0"
rust-embed = "8.5.0"
tokio = { version = "1.40.0", features = ["full"] }

rustemon = { version = "3.4.1", default-features = false, features = [
    "in-memory-cache",
] }
dirs = "5.0.1"
futures = "0.3.31"
reqwest = { version = "0.12.8", features = ["json"] }
serde = { version = "1.0.202", features = ["serde_derive"] }
serde_json = "1.0.128"

[dependencies.i18n-embed]
version = "0.15"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["dbus-config", "tokio", "winit", "wgpu"]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
